//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: 4.0.30319.34011
//
//     Los cambios de este archivo pueden provocar un comportamiento inesperado y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace At_Windows_Startup.Properties
{


    /// <summary>
    ///   Clase de recurso fuertemente tipado para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Devuelve la instancia ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("At_Windows_Startup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos usando esta clase de recursos fuertemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
		
		/// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string UC1 {
            get {
                return ResourceManager.GetString("UC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualización descargada.
        /// </summary>
        internal static string UC10 {
            get {
                return ResourceManager.GetString("UC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizando desde la versión.
        /// </summary>
        internal static string UC11 {
            get {
                return ResourceManager.GetString("UC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a la última versión disponible.
        /// </summary>
        internal static string UC12 {
            get {
                return ResourceManager.GetString("UC12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar y salir.
        /// </summary>
        internal static string UC2 {
            get {
                return ResourceManager.GetString("UC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobando actualizaciones....
        /// </summary>
        internal static string UC3 {
            get {
                return ResourceManager.GetString("UC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo comprobar si existen actualizaciones
        ///Compruebe que dispone de conexión a internet.
        /// </summary>
        internal static string UC4 {
            get {
                return ResourceManager.GetString("UC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha encontrado una nueva versión
        ///Haga clic en actualizar para descargarla atuomáticamente.
        /// </summary>
        internal static string UC5 {
            get {
                return ResourceManager.GetString("UC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya está utilizando la última versión
        ///No es necesario actualizar.
        /// </summary>
        internal static string UC6 {
            get {
                return ResourceManager.GetString("UC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizando....
        /// </summary>
        internal static string UC7 {
            get {
                return ResourceManager.GetString("UC7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El programa se ha descargado correctamente.
        ///                
        ///Borre la versión actual y extraiga el archivo comprimido descargado en:.
        /// </summary>
        internal static string UC8 {
            get {
                return ResourceManager.GetString("UC8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea abrir la carpeta?.
        /// </summary>
        internal static string UC9 {
            get {
                return ResourceManager.GetString("UC9", resourceCulture);
            }
        }
    }
}
